cleartext:
  enabled: true
  listen_addr: ":8080"

algo: rr

upstreams:
  - http://demo-upstream1:80
  - http://demo-upstream2:80

tls:
  enabled: true
  listen_addr: ":8443"
  cert: "certs/cert.pem"
  key: "certs/key.pem"

rate_limit:
  enabled: true
  rps: 100
  burst: 20
  per_ip: true
