cleartext:
  enabled: true
  listen_addr: ":8080"

algo: lc

upstreams:
  - http://demo-upstream1:80
  - http://demo-upstream2:80
  # - http://localhost:50051

tls:
  enabled: true
  listen_addr: ":8443"
  cert: "certs/cert.pem"
  key: "certs/key.pem"

metrics:
  enabled: true
  listen_addr: ":2112"

rate_limit:
  enabled: true
  rps: 10
  burst: 5
  per_ip: true
