services:
  proxy:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - upstream1
      - upstream2

  upstream1:
    image: nginx
    ports:
      - "9000:80"

  upstream2:
    image: nginx
    ports:
      - "9001:80"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/dashboards/proxy.json:/var/lib/grafana/dashboards/proxy.json
    depends_on:
      - prometheus
